### PR TITLE
Development

### PR DESCRIPTION
**Pull request by lBuggie**
Project for CSS backgrounds and gradients with a clone of Apple landing page from 2014 completed.

The following was taken into account for this project:
- Positioning is done with flex, grid, and float.
- Background images added where necessary.
- The navbar has a gradient background.
- Images were used in the same places as in the original.
- Linters and HTML validation suggestions implemented.

### CODE REVIEW

**Comment by lBuggie** [comment]
- Images were replaced with divs with background.
- README file was updated.

**Comment by lBuggie** [comment]
Changes requested were made.

- a tags added around divs.
- added cursor pointer to span around hero section, since adding a tag affected the styles that were already applied.

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @lBuggie , 👋

## Good job implementing the changes on this project! 👍

- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.

- Pay attention to the error related to the `<span>` tag enclosing the `<section>` tag. You shouldn't do this (and actually, you don't need it! It works ok if you delete it)

- Your bottom images are not showing. There is no need to store them in your repo, you could also use the original url to link them. Please fix this. 
I tried using different browsers, opening your project with githack and also downloading it and still can't see the images.
Screenshot from 2020-02-26 19-51-50

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- It is a good practice to enclose the main content in a `<main>` tag. You could include here the two sections you have. Don't put in here the nav or the footer.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Pull request merged**
